export const emailText="E-mail"
export const passwordText="Password"
export const confirmPasswordText="Confirm Password"
export const firstNameText="First Name"
export const lastNameText="Last Name"
export const usernameText="Username"